import { createSlice } from "@reduxjs/toolkit";

// Create a slice for managing user-related state
const userSlice = createSlice({
  // Name of the slice
  name: "user",

  // Initial state of the user slice
  initialState: {
    userName: "",               // User's name
    monthlyBudget: "",         // Overall monthly budget
    categoricalBudget: {       // Budgets for specific categories
      food: "",
      travel: "",
      entertainment: "",
      others: "",
    },
    activeFilter: "all",       // Currently selected filter for viewing transactions
  },

  // Reducers to update parts of the user state
  reducers: {
    /**
     * Updates the user's name.
     * @param {Object} state - Current state
     * @param {string} action.payload - New user name
     */
    updateUserName: (state, action) => {
      state.userName = action.payload;
    },

    /**
     * Updates the overall monthly budget.
     * @param {Object} state - Current state
     * @param {string} action.payload - New monthly budget value
     */
    updateMonthlyBudget: (state, action) => {
      state.monthlyBudget = action.payload;
    },

    /**
     * Updates specific category budgets.
     * @param {Object} state - Current state
     * @param {Object} action.payload - Object with updated category budgets
     */
    updateCategoricalBudget: (state, action) => {
      state.categoricalBudget = {
        ...state.categoricalBudget,
        ...action.payload,
      };

      return state;
    },

    /**
     * Updates the active filter for viewing transactions.
     * @param {Object} state - Current state
     * @param {string} action.payload - New filter value
     */
    updateActiveFilter: (state, action) => {
      state.activeFilter = action.payload;
    },

    /**
     * Resets all user data including budgets and filter.
     * @param {Object} state - Current state
     */
    resetAllBudget: (state) => {
      state.userName = "";
      state.monthlyBudget = "";
      state.categoricalBudget = {
        food: "",
        travel: "",
        entertainment: "",
        others: "",
      };
      state.activeFilter = "all";
    },
  },
});

// Export action creators generated by createSlice
export const {
  updateUserName,
  updateMonthlyBudget,
  updateCategoricalBudget,
  updateActiveFilter,
  resetAllBudget,
} = userSlice.actions;

// Export reducer function to be included in the store
export default userSlice.reducer;
